dist: xenial
language: java

notifications:
  email: false

jdk:
  - openjdk10

cache:
  directories:
    - $HOME/.m2

services:
  - xvfb

script:
  - mvn test -B
  - mvn clean package -DskipTests=true
  - travis_wait 60 ./smoketest/smoke_test.sh
